import {createHash} from 'node:crypto';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {indexedDB} from 'fake-indexeddb';import {JSDOM} from 'jsdom';
import * as c from '../releases/20261009-integrity-r2/ledger-core.3.1.0.js';import * as k from '../releases/20261009-integrity-r2/crypto.3.1.0.js';import * as store from '../releases/20261009-integrity-r2/storage.3.1.0.js';
import {migrateLegacyState} from '../releases/20261009-integrity-r2/migrations.3.1.0.js';
import {buildLedgerReportPdf} from '../releases/20261009-integrity-r2/pdf-report-v2.3.1.1.js';import {pdfText} from '../releases/20261009-integrity-r2/pdf-unicode.3.1.1.js';
globalThis.indexedDB=indexedDB;globalThis.BroadcastChannel=undefined;globalThis.localStorage={getItem:()=>null};
function fixture(){const s=c.newEmptyState();s.creditors=[{id:'c',name:'Synthetic'}];return s;}
function tx(id,type,n,extra={}){return {...c.txBase({creditorId:'c',type,amountHalalas:n,effectiveDate:'2026-10-01'}),id,...extra};}
function amount(state){return c.overallSummary(state).remaining;}
const appSource=fs.readFileSync(new URL('../releases/20261009-integrity-r2/app.3.1.0.js',import.meta.url),'utf8');
const reportSource=fs.readFileSync(new URL('../releases/20261009-integrity-r2/report-tools.3.1.1.js',import.meta.url),'utf8');
function appContext(){const dom=new JSDOM(fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),{url:'https://example.invalid/ledgerly-app/'});const w=dom.window;const ctx={...c,...k,...store,BUILD_ID:'TEST',window:w,document:w.document,history:w.history,location:w.location,navigator:w.navigator,Event:w.Event,File:w.File,FormData:w.FormData,HTMLElement:w.HTMLElement,HTMLFormElement:w.HTMLFormElement,MutationObserver:w.MutationObserver,localStorage:w.localStorage,matchMedia:()=>({matches:true,addEventListener(){}}),requestAnimationFrame:()=>{},setTimeout:()=>0,clearTimeout(){},console,crypto:globalThis.crypto,CSS:{escape:v=>v},setLanguage(){},t:v=>v,Blob,URL};vm.createContext(ctx);vm.runInContext(appSource.replace(/^import[\s\S]*?;\n/gm,'').replace(/bootstrap\(\)\.catch\(err=>setSafeMode\('Ledgerly could not start safely\.',err\)\);/,''),ctx);vm.runInContext('render=()=>{};',ctx);return {ctx,dom,run:code=>vm.runInContext(code,ctx)};}
test('baseline balances are unchanged',()=>{const s=fixture();s.transactions=[tx('d','debt',1348216),tx('p','payment',101000,{allocations:[{debtId:'d',amountHalalas:101000}]})];assert.equal(amount(s),1247216);assert.equal(c.validateState(s),true);});
test('Base64 roundtrip at advertised 10 MiB limit',()=>{const bytes=new Uint8Array(10*1024*1024);bytes[bytes.length-1]=203;assert.deepEqual(k.base64ToBytes(k.bytesToBase64(bytes)),bytes);});
test('large encrypted ledger roundtrip',async()=>{const dek=await k.importDek(new Uint8Array(32));const s={notes:'a'.repeat(300000)};assert.deepEqual(await k.decryptJson(await k.encryptJson(s,dek),dek),s);});
test('negative or excessive allocations cannot be saved',()=>{for(const allocated of [-1,11000]){const s=fixture();s.transactions=[tx('d','debt',10000),tx('p','payment',2000,{allocations:[{debtId:'d',amountHalalas:allocated}]})];assert.throws(()=>c.validateState(s));}});
test('correction below allocated debt is rejected',()=>{const s=fixture();s.transactions=[tx('d','debt',5000),tx('d2','debt',10000),tx('p','payment',8000,{allocations:[{debtId:'d',amountHalalas:8000}]})];assert.throws(()=>c.validateState(s));});
test('decreases reconcile debt and category exposure',()=>{const s=fixture();s.transactions=[tx('d','debt',10000,{category:'Housing'}),tx('a','adjustment',3000,{adjustmentDirection:'decrease',category:'Utilities'})];assert.equal(c.debtRemaining(s,'d'),7000);assert.equal(c.categoryBalances(s).reduce((n,x)=>n+x.remaining,0),amount(s));});
test('unallocated increases are explicit exposure and consumed by payments',()=>{const s=fixture();s.transactions=[tx('d','debt',10000),tx('a','adjustment',5000,{category:'Fees'}),tx('p','payment',12000,{allocations:[{debtId:'d',amountHalalas:10000}]})];assert.equal(c.validateState(s),true);assert.equal(amount(s),3000);assert.deepEqual(c.categoryBalances(s),[{category:'Fees',remaining:3000}]);});
test('500 valid mixed ledgers keep categories equal to creditor balance',()=>{for(let i=1;i<=500;i++){const s=fixture();const debt=10000+i,paid=i%2000,decrease=i%1000,increase=i%500;s.transactions=[tx('d','debt',debt,{category:'Housing'}),tx('p','payment',paid||1,{allocations:[{debtId:'d',amountHalalas:paid||1}]}),tx('a','adjustment',decrease||1,{adjustmentDirection:'decrease',category:'Other'}),tx('b','adjustment',increase||1,{category:'Fees'})];assert.equal(c.validateState(s),true);assert.equal(c.categoryBalances(s).reduce((n,x)=>n+x.remaining,0),amount(s));}});
test('future schema and invalid dates rejected before normalization',()=>{const s=fixture();s.schemaVersion=999;assert.throws(()=>c.reconcileState(s));s.schemaVersion=4;s.transactions=[tx('d','debt',1,{effectiveDate:'2026-02-30'})];assert.throws(()=>c.validateState(c.reconcileState(s)));assert.equal(c.safeDate('2026-99-99'),'');});
test('duplicate, cross-creditor and circular reversals rejected',()=>{for(const bad of ['duplicate','cross','circular']){const s=fixture();s.creditors.push({id:'other',name:'Other'});s.transactions=[tx('d','debt',10000),tx('p','payment',2000),tx('r','reversal',2000,{reversedTransactionId:bad==='circular'?'r':'p',creditorId:bad==='cross'?'other':'c'})];if(bad==='duplicate')s.transactions.push(tx('r2','reversal',2000,{reversedTransactionId:'p'}));assert.throws(()=>c.validateState(s));}});
test('archiving a card does not remove outstanding liabilities',()=>{const s=fixture();s.creditors[0].archivedAt='2026-10-09';s.transactions=[tx('d','debt',10000)];assert.equal(amount(s),10000);assert.equal(c.overallSummary(s,'2026-10-09').remaining,10000);});
test('cash paid stays separate from waived',()=>{const s=fixture();s.transactions=[tx('d','debt',10000),tx('w','waiver',1000)];const summary=c.creditorSummary(s,'c');assert.equal(summary.paid,0);assert.equal(summary.waivers,1000);assert.equal(summary.remaining,9000);});
test('weekly and monthly plans produce different targets; paid debt ignored',()=>{const s=fixture();s.transactions=[tx('d','debt',100000,{plan:{amountHalalas:10000,frequency:'Weekly'}})];const weekly=c.paymentPlanEstimate(s,'c');s.transactions[0].plan.frequency='Monthly';const monthly=c.paymentPlanEstimate(s,'c');assert.ok(weekly.cycles<monthly.cycles);});
test('settled debt does not determine next due date',()=>{const s=fixture();s.transactions=[tx('d','debt',10000,{dueDate:'2026-10-01'}),tx('d2','debt',10000,{dueDate:'2026-12-01'}),tx('p','payment',10000,{allocations:[{debtId:'d',amountHalalas:10000}]})];assert.equal(c.creditorSummary(s,'c').nextDue,'2026-12-01');});
test('CSV treats formula-like labels as text',()=>{const s=fixture();s.creditors[0].name='=1+1';s.transactions=[tx('d','debt',1)];assert.ok(c.humanCsv(s).includes("\"'=1+1\""));});
test('legacy migration preserves named creditor, extra payments and numeric IDs',()=>{const input={creditors:[{id:1,name:"Samha's School"},{id:2,name:'Electricity'}],debts:[{id:'d1',creditorId:1,amount:100},{id:'d2',creditorId:2,amount:600},{id:'d3',creditorId:2,amount:1400},{id:'d4',creditorId:2,amount:2000}],payments:[{id:'p1',creditorId:2,amount:50}]};const s=migrateLegacyState(input);assert.equal(s.creditors.length,2);assert.equal(s.transactions.length,5);assert.equal(c.overallSummary(s).paid,5000);});
test('financial merge conflicts include adjustment direction',()=>{const {ctx,run}=appContext();const s=fixture();s.transactions=[tx('d','debt',10000),tx('a','adjustment',1000)];ctx.fixture=s;run('state=fixture');ctx.incoming=c.deepClone(s);ctx.incoming.transactions[1].adjustmentDirection='decrease';assert.equal(run('analyzeMerge(incoming).conflicts.length'),1);});
test('lock removes every sensitive overlay and title',()=>{const {ctx,dom,run}=appContext();ctx.fixture=fixture();run('state=fixture;record={encrypted:true};dek={};');for(const id of ['ledgerlyFinancialGuard','ledgerlyReportOverlay']){const el=dom.window.document.createElement('div');el.id=id;el.innerHTML='<input type="password" value="SYNTHETIC">';dom.window.document.body.append(el);}ctx.window.addEventListener('ledgerly-locked',()=>dom.window.document.querySelectorAll('#ledgerlyFinancialGuard,#ledgerlyReportOverlay').forEach(el=>el.remove()));run('lockApp()');assert.equal(ctx.document.title,'Ledgerly · Locked');assert.equal(ctx.document.querySelector('#ledgerlyFinancialGuard'),null);assert.equal(run('state'),null);});
test('all close paths settle duplicate confirmation',async()=>{const {run}=appContext();const result=run("confirmAsync({text:'Synthetic duplicate'})");run('closeModal()');assert.equal(await result,false);});
test('commit rejects conflicts so no caller enters success path',async()=>{const {ctx,run}=appContext();ctx.fixture=fixture();run('state=fixture;record={revision:1};');run('beginOperation=async()=>"op";failOperation=async()=>{};buildRecordFromState=async()=>({});saveStateRecord=async()=>{throw new RevisionConflictError()};reloadFromStorage=async()=>{};');await assert.rejects(run("commit({event:'Synthetic',mutate:async next=>{next.settings.theme='dark'}})"),{name:'RevisionConflictError'});});
test('complete before/after correction is stored in audit',async()=>{const {ctx,run}=appContext();const s=fixture();s.transactions=[tx('d','debt',10000,{notes:'before'})];ctx.fixture=s;run('state=fixture;record={revision:1};beginOperation=async()=>"op";buildRecordFromState=async next=>({payload:next,revision:2});saveStateRecord=async r=>r;');await run("commit({event:'Transaction corrected',entityType:'transaction',entityId:'d',mutate:async next=>{next.transactions[0].notes='after'}})");assert.equal(run('state.audit[0].before.notes'),'before');assert.equal(run('state.audit[0].after.notes'),'after');});
test('Arabic PDF text uses embedded Unicode glyphs, not question marks',()=>{const text=pdfText('أحمد محمد');assert.equal(text.font,'F3');assert.match(text.token,/^<[a-f0-9]+>$/);});
test('invalid evidence reference rejected',()=>{const s=fixture();s.transactions=[tx('d','debt',1,{attachmentIds:['missing']})];assert.throws(()=>c.validateAttachments(s,[]));});
test('snapshot preserves deleted evidence; state and attachments roll back atomically',async()=>{const s=fixture();s.transactions=[tx('d','debt',1,{attachmentIds:['a']})];await store.saveStateRecord({revision:1,payload:s},{attachments:[{id:'a',transactionId:'d',creditorId:'c',data:'QQ=='}]});const noFile=c.deepClone(s);noFile.transactions[0].attachmentIds=[];await store.saveStateRecord({revision:2,payload:noFile},{expectedRevision:1,snapshotReason:'Before removal',deleteAttachmentIds:['a']});const snap=(await store.listSnapshots())[0];assert.equal(snap.attachments[0].data,'QQ==');assert.equal(await store.getAttachment('a'),null);await store.saveStateRecord({...snap.record,revision:3},{expectedRevision:2,attachments:snap.attachments});assert.equal((await store.getAttachment('a')).data,'QQ==');assert.equal((await store.getStateRecord()).payload.transactions[0].attachmentIds[0],'a');});
test('failure in attachment mutation aborts the state write too',async()=>{const before=await store.getStateRecord();await assert.rejects(store.saveStateRecord({revision:before.revision+1,payload:{changed:true}},{expectedRevision:before.revision,attachments:[{id:'valid'},{}]}));assert.equal((await store.getStateRecord()).revision,before.revision);assert.equal((await store.getAttachment('a')).data,'QQ==');});
test('concurrent reference writes have unique revision lease',async()=>{const fn=reportSource.slice(reportSource.indexOf('async function persistReportRef('),reportSource.indexOf('function typeLabel('));const rec=await store.getStateRecord();const ctx={...store,...k,localStorage:{setItem(){}},window:{dispatchEvent(){}},Event:globalThis.Event,r:rec,s:rec.payload};vm.createContext(ctx);vm.runInContext(fn,ctx);await vm.runInContext("persistReportRef(r,s,null,{seq:{infographic:1}})",ctx);assert.equal((await store.getStateRecord()).revision,rec.revision+1);await assert.rejects(vm.runInContext("persistReportRef(r,s,null,{seq:{infographic:1}})",ctx),{name:'RevisionConflictError'});});
test('safe-mode restore reencrypts evidence and preserves the current security keys',async()=>{
 const old=await store.getStateRecord(),currentKey=await k.importDek(new Uint8Array(32).fill(1)),backupKey=await k.importDek(new Uint8Array(32).fill(2));const current=fixture();current.meta.revision=old.revision+1;
 const security={sentinel:'current security'};const encryptedRecord=await store.saveStateRecord({id:'current',revision:current.meta.revision,encrypted:true,envelope:await k.encryptJson(current,currentKey),security},{expectedRevision:old.revision});
 const imported=fixture();imported.transactions=[tx('new','debt',700,{attachmentIds:['evidence']})];const file=await k.encryptAttachmentRecord({id:'evidence',transactionId:'new',creditorId:'c',size:1},new Uint8Array([65]),backupKey);
 const {ctx,run}=appContext();Object.assign(ctx,{fixtureRecord:encryptedRecord,currentKey,securityFixture:security,backupKey,importedFixture:imported,fileFixture:file});
 run("record=fixtureRecord;state=null;safeMode=true;dek=currentKey;security=securityFixture;ui.modal={ctx:{state:importedFixture,dek:backupKey,obj:{createdAt:'2026-10-09',attachments:[fileFixture]}}};authorizeProtected=(label,cb)=>{globalThis.restoreCallback=cb};");run('applyRestore()');await ctx.restoreCallback();
 const saved=await store.getStateRecord();assert.deepEqual(saved.security,security);assert.equal((await k.decryptJson(saved.envelope,currentKey)).transactions[0].amountHalalas,700);assert.deepEqual(new Uint8Array(await k.decryptAttachmentBytes(await store.getAttachment('evidence'),currentKey)),new Uint8Array([65]));
});
test('release manifest hashes and relative module imports are complete',()=>{
 const release=JSON.parse(fs.readFileSync(new URL('../LEDGERLY_RELEASE.json',import.meta.url),'utf8'));for(const entry of release.files){const bytes=fs.readFileSync(new URL('../'+entry.name,import.meta.url));assert.equal(bytes.length,entry.bytes);assert.equal(createHash("sha256").update(bytes).digest("hex"),entry.sha256);}
 const dir=new URL('../releases/20261009-integrity-r2/',import.meta.url);for(const name of fs.readdirSync(dir).filter(n=>n.endsWith('.js'))){const src=fs.readFileSync(new URL(name,dir),'utf8');for(const match of src.matchAll(/(?:from\s*|import\s*)['"](\.\/[^'"]+)['"]/g))assert.ok(fs.existsSync(new URL(match[1],dir)),`${name}: ${match[1]}`);}
});
test('install waits for an explicit update and offline navigation uses one cached shell',async()=>{
 const handlers={},shell={cached:true};let skips=0,added=[];const ctx={self:{location:{origin:'https://example.invalid'},clients:{claim:async()=>{}},skipWaiting(){skips++},addEventListener:(name,cb)=>handlers[name]=cb},URL,caches:{open:async()=>({addAll:async list=>{added=list},match:async()=>shell}),keys:async()=>[],delete:async()=>true},fetch:async()=>{throw new Error('offline')}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(new URL('../service-worker.js',import.meta.url),'utf8'),ctx);let done;handlers.install({waitUntil:p=>done=p});await done;assert.equal(skips,0);assert.ok(added.includes('./releases/20261009-integrity-r2/app.3.1.0.js'));let response;handlers.fetch({request:{method:'GET',url:'https://example.invalid/ledgerly-app/',mode:'navigate'},respondWith:p=>response=p});assert.equal(await response,shell);handlers.message({data:{type:'SKIP_WAITING'}});assert.equal(skips,1);
});
function financialGuardContext(){
 const dom=new JSDOM('<div id="app"></div><form id="debtForm"><input name="amount" value="100"><input name="evidence" type="file"><button type="submit">Save</button></form><form id="paymentForm"><input name="amount" value="25"><button type="submit">Save</button></form>');const w=dom.window;let attempts=0,saves=0;
 const context={document:w.document,window:w,HTMLFormElement:w.HTMLFormElement,getStateRecord:async()=>({encrypted:true,security:{}}),unlockSecurity:async(_s,password)=>{attempts++;if(password!=='test-correct')throw new Error('Wrong password')},queueMicrotask,setTimeout:fn=>{fn();return 0},console:{error(){}}};vm.createContext(context);const source=fs.readFileSync(new URL('../releases/20261009-integrity-r2/financial-action-guard.3.1.1.js',import.meta.url),'utf8');vm.runInContext(source.replace(/^import.*;\n/gm,''),context);w.document.addEventListener('submit',e=>{if(['debtForm','paymentForm'].includes(e.target.id)){e.preventDefault();saves++;}});
 return {w,attempts:()=>attempts,saves:()=>saves};
}
test('every debt/payment submit requires a fresh password and cancel preserves inputs',()=>{
 for(const id of ['debtForm','paymentForm']){const t=financialGuardContext(),form=t.w.document.getElementById(id);form.requestSubmit();assert.ok(t.w.document.getElementById('ledgerlyFinancialGuard'));assert.equal(t.saves(),0);t.w.document.getElementById('fgCancel').click();assert.equal(form.elements.amount.value,id==='debtForm'?'100':'25');assert.ok(form.isConnected);assert.equal(t.saves(),0);form.requestSubmit();assert.ok(t.w.document.getElementById('ledgerlyFinancialGuard'));}
});
test('wrong password saves nothing; correct password authorizes exactly one unchanged form submission',async()=>{
 for(const id of ['debtForm','paymentForm']){const t=financialGuardContext(),form=t.w.document.getElementById(id);const evidence=form.querySelector('[type=file]');const file=new t.w.File(['evidence'],'test.txt');if(evidence)Object.defineProperty(evidence,'files',{value:[file]});form.requestSubmit();t.w.document.getElementById('fgPassword').value='incorrect';t.w.document.getElementById('fgAuthForm').requestSubmit();await new Promise(resolve=>setImmediate(resolve));assert.equal(t.saves(),0);assert.equal(form.elements.amount.value,id==='debtForm'?'100':'25');if(evidence)assert.equal(evidence.files[0],file);assert.equal(t.w.document.getElementById('fgError').textContent,'Incorrect master password.');t.w.document.getElementById('fgPassword').value='test-correct';t.w.document.getElementById('fgAuthForm').requestSubmit();await new Promise(resolve=>setImmediate(resolve));assert.equal(t.saves(),1);assert.equal(form.dataset.ledgerlyFinancialAuthorized,undefined);form.requestSubmit();assert.ok(t.w.document.getElementById('ledgerlyFinancialGuard'));assert.equal(t.saves(),1);}
});
test('locking during password check cannot authorize the pending debt',async()=>{
 const t=financialGuardContext(),form=t.w.document.getElementById('debtForm');form.requestSubmit();t.w.document.getElementById('fgPassword').value='test-correct';t.w.document.getElementById('fgAuthForm').requestSubmit();t.w.document.getElementById('app').hidden=true;t.w.dispatchEvent(new t.w.Event('ledgerly-locked'));await new Promise(resolve=>setImmediate(resolve));assert.equal(t.saves(),0);assert.equal(form.dataset.ledgerlyFinancialAuthorized,undefined);
});
