import {createHash} from 'node:crypto';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {indexedDB} from 'fake-indexeddb';import {JSDOM} from 'jsdom';
import * as c from '../releases/20261009-integrity-r4/ledger-core.3.1.0.js';import * as k from '../releases/20261009-integrity-r4/crypto.3.1.0.js';import * as store from '../releases/20261009-integrity-r4/storage.3.1.0.js';
import {migrateLegacyState} from '../releases/20261009-integrity-r4/migrations.3.1.0.js';
import {buildLedgerReportPdf} from '../releases/20261009-integrity-r4/pdf-report-v2.3.1.1.js';import {pdfText} from '../releases/20261009-integrity-r4/pdf-unicode.3.1.1.js';
globalThis.indexedDB=indexedDB;globalThis.BroadcastChannel=undefined;globalThis.localStorage={getItem:()=>null};
function fixture(){const s=c.newEmptyState();s.creditors=[{id:'c',name:'Synthetic'}];return s;}
function tx(id,type,n,extra={}){return {...c.txBase({creditorId:'c',type,amountHalalas:n,effectiveDate:'2026-10-01'}),id,...extra};}
function amount(state){return c.overallSummary(state).remaining;}
const appSource=fs.readFileSync(new URL('../releases/20261009-integrity-r4/app.3.1.0.js',import.meta.url),'utf8');
const reportSource=fs.readFileSync(new URL('../releases/20261009-integrity-r4/report-tools.3.1.1.js',import.meta.url),'utf8');
function appContext(){const dom=new JSDOM(fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),{url:'https://example.invalid/ledgerly-app/'});const w=dom.window;const ctx={...c,...k,...store,BUILD_ID:'TEST',window:w,document:w.document,history:w.history,location:w.location,navigator:w.navigator,Event:w.Event,File:w.File,FormData:w.FormData,HTMLElement:w.HTMLElement,HTMLFormElement:w.HTMLFormElement,MutationObserver:w.MutationObserver,localStorage:w.localStorage,matchMedia:()=>({matches:true,addEventListener(){}}),requestAnimationFrame:()=>{},setTimeout:()=>0,clearTimeout(){},console,crypto:globalThis.crypto,CSS:{escape:v=>v},setLanguage(){},t:v=>v,Blob,URL};vm.createContext(ctx);vm.runInContext(appSource.replaceAll('import.meta.url',JSON.stringify('https://example.invalid/ledgerly-app/releases/20261009-integrity-r4/app.3.1.0.js')).replace(/^import[\s\S]*?;\n/gm,'').replace(/bootstrap\(\)\.catch\(err=>setSafeMode\('Ledgerly could not start safely\.',err\)\);/,''),ctx);vm.runInContext('render=()=>{};',ctx);return {ctx,dom,run:code=>vm.runInContext(code,ctx)};}
test('baseline balances are unchanged',()=>{const s=fixture();s.transactions=[tx('d','debt',1348216),tx('p','payment',101000,{allocations:[{debtId:'d',amountHalalas:101000}]})];assert.equal(amount(s),1247216);assert.equal(c.validateState(s),true);});
test('Base64 roundtrip at advertised 10 MiB limit',()=>{const bytes=new Uint8Array(10*1024*1024);bytes[bytes.length-1]=203;assert.deepEqual(k.base64ToBytes(k.bytesToBase64(bytes)),bytes);});
test('large encrypted ledger roundtrip',async()=>{const dek=await k.importDek(new Uint8Array(32));const s={notes:'a'.repeat(300000)};assert.deepEqual(await k.decryptJson(await k.encryptJson(s,dek),dek),s);});
test('negative or excessive allocations cannot be saved',()=>{for(const allocated of [-1,11000]){const s=fixture();s.transactions=[tx('d','debt',10000),tx('p','payment',2000,{allocations:[{debtId:'d',amountHalalas:allocated}]})];assert.throws(()=>c.validateState(s));}});
test('correction below allocated debt is rejected',()=>{const s=fixture();s.transactions=[tx('d','debt',5000),tx('d2','debt',10000),tx('p','payment',8000,{allocations:[{debtId:'d',amountHalalas:8000}]})];assert.throws(()=>c.validateState(s));});
test('decreases reconcile debt and category exposure',()=>{const s=fixture();s.transactions=[tx('d','debt',10000,{category:'Housing'}),tx('a','adjustment',3000,{adjustmentDirection:'decrease',category:'Utilities'})];assert.equal(c.debtRemaining(s,'d'),7000);assert.equal(c.categoryBalances(s).reduce((n,x)=>n+x.remaining,0),amount(s));});
test('unallocated increases are explicit exposure and consumed by payments',()=>{const s=fixture();s.transactions=[tx('d','debt',10000),tx('a','adjustment',5000,{category:'Fees'}),tx('p','payment',12000,{allocations:[{debtId:'d',amountHalalas:10000}]})];assert.equal(c.validateState(s),true);assert.equal(amount(s),3000);assert.deepEqual(c.categoryBalances(s),[{category:'Fees',remaining:3000}]);});
test('500 valid mixed ledgers keep categories equal to creditor balance',()=>{for(let i=1;i<=500;i++){const s=fixture();const debt=10000+i,paid=i%2000,decrease=i%1000,increase=i%500;s.transactions=[tx('d','debt',debt,{category:'Housing'}),tx('p','payment',paid||1,{allocations:[{debtId:'d',amountHalalas:paid||1}]}),tx('a','adjustment',decrease||1,{adjustmentDirection:'decrease',category:'Other'}),tx('b','adjustment',increase||1,{category:'Fees'})];assert.equal(c.validateState(s),true);assert.equal(c.categoryBalances(s).reduce((n,x)=>n+x.remaining,0),amount(s));}});
test('future schema and invalid dates rejected before normalization',()=>{const s=fixture();s.schemaVersion=999;assert.throws(()=>c.reconcileState(s));s.schemaVersion=4;s.transactions=[tx('d','debt',1,{effectiveDate:'2026-02-30'})];assert.throws(()=>c.validateState(c.reconcileState(s)));assert.equal(c.safeDate('2026-99-99'),'');});
test('duplicate, cross-creditor and circular reversals rejected',()=>{for(const bad of ['duplicate','cross','circular']){const s=fixture();s.creditors.push({id:'other',name:'Other'});s.transactions=[tx('d','debt',10000),tx('p','payment',2000),tx('r','reversal',2000,{reversedTransactionId:bad==='circular'?'r':'p',creditorId:bad==='cross'?'other':'c'})];if(bad==='duplicate')s.transactions.push(tx('r2','reversal',2000,{reversedTransactionId:'p'}));assert.throws(()=>c.validateState(s));}});
test('archiving a card does not remove outstanding liabilities',()=>{const s=fixture();s.creditors[0].archivedAt='2026-10-09';s.transactions=[tx('d','debt',10000)];assert.equal(amount(s),10000);assert.equal(c.overallSummary(s,'2026-10-09').remaining,10000);});
test('cash paid stays separate from waived',()=>{const s=fixture();s.transactions=[tx('d','debt',10000),tx('w','waiver',1000)];const summary=c.creditorSummary(s,'c');assert.equal(summary.paid,0);assert.equal(summary.waivers,1000);assert.equal(summary.remaining,9000);});
test('weekly and monthly plans produce different targets; paid debt ignored',()=>{const s=fixture();s.transactions=[tx('d','debt',100000,{plan:{amountHalalas:10000,frequency:'Weekly'}})];const weekly=c.paymentPlanEstimate(s,'c');s.transactions[0].plan.frequency='Monthly';const monthly=c.paymentPlanEstimate(s,'c');assert.ok(weekly.cycles<monthly.cycles);});
test('settled debt does not determine next due date',()=>{const s=fixture();s.transactions=[tx('d','debt',10000,{dueDate:'2026-10-01'}),tx('d2','debt',10000,{dueDate:'2026-12-01'}),tx('p','payment',10000,{allocations:[{debtId:'d',amountHalalas:10000}]})];assert.equal(c.creditorSummary(s,'c').nextDue,'2026-12-01');});
test('CSV treats formula-like labels as text',()=>{const s=fixture();s.creditors[0].name='=1+1';s.transactions=[tx('d','debt',1)];assert.ok(c.humanCsv(s).includes("\"'=1+1\""));});
test('legacy migration preserves named creditor, extra payments and numeric IDs',()=>{const input={creditors:[{id:1,name:"Samha's School"},{id:2,name:'Electricity'}],debts:[{id:'d1',creditorId:1,amount:100},{id:'d2',creditorId:2,amount:600},{id:'d3',creditorId:2,amount:1400},{id:'d4',creditorId:2,amount:2000}],payments:[{id:'p1',creditorId:2,amount:50}]};const s=migrateLegacyState(input);assert.equal(s.creditors.length,2);assert.equal(s.transactions.length,5);assert.equal(c.overallSummary(s).paid,5000);});
test('financial merge conflicts include adjustment direction',()=>{const {ctx,run}=appContext();const s=fixture();s.transactions=[tx('d','debt',10000),tx('a','adjustment',1000)];ctx.fixture=s;run('state=fixture');ctx.incoming=c.deepClone(s);ctx.incoming.transactions[1].adjustmentDirection='decrease';assert.equal(run('analyzeMerge(incoming).conflicts.length'),1);});
test('lock removes every sensitive overlay and title',()=>{const {ctx,dom,run}=appContext();ctx.fixture=fixture();run('state=fixture;record={encrypted:true};dek={};');for(const id of ['ledgerlyFinancialGuard','ledgerlyReportOverlay']){const el=dom.window.document.createElement('div');el.id=id;el.innerHTML='<input type="password" value="SYNTHETIC">';dom.window.document.body.append(el);}ctx.window.addEventListener('ledgerly-locked',()=>dom.window.document.querySelectorAll('#ledgerlyFinancialGuard,#ledgerlyReportOverlay').forEach(el=>el.remove()));run('lockApp()');assert.equal(ctx.document.title,'Ledgerly · Locked');assert.equal(ctx.document.querySelector('#ledgerlyFinancialGuard'),null);assert.equal(run('state'),null);});
test('all close paths settle duplicate confirmation',async()=>{const {run}=appContext();const result=run("confirmAsync({text:'Synthetic duplicate'})");run('closeModal()');assert.equal(await result,false);});
test('commit rejects conflicts so no caller enters success path',async()=>{const {ctx,run}=appContext();ctx.fixture=fixture();run('state=fixture;record={revision:1};');run('beginOperation=async()=>"op";failOperation=async()=>{};buildRecordFromState=async()=>({});saveStateRecord=async()=>{throw new RevisionConflictError()};reloadFromStorage=async()=>{};');await assert.rejects(run("commit({event:'Synthetic',mutate:async next=>{next.settings.theme='dark'}})"),{name:'RevisionConflictError'});});
test('complete before/after correction is stored in audit',async()=>{const {ctx,run}=appContext();const s=fixture();s.transactions=[tx('d','debt',10000,{notes:'before'})];ctx.fixture=s;run('state=fixture;record={revision:1};beginOperation=async()=>"op";buildRecordFromState=async next=>({payload:next,revision:2});saveStateRecord=async r=>r;');await run("commit({event:'Transaction corrected',entityType:'transaction',entityId:'d',mutate:async next=>{next.transactions[0].notes='after'}})");assert.equal(run('state.audit[0].before.notes'),'before');assert.equal(run('state.audit[0].after.notes'),'after');});
test('Arabic PDF text uses embedded Unicode glyphs, not question marks',()=>{const text=pdfText('أحمد محمد');assert.equal(text.font,'F3');assert.match(text.token,/^<[a-f0-9]+>$/);});
test('invalid evidence reference rejected',()=>{const s=fixture();s.transactions=[tx('d','debt',1,{attachmentIds:['missing']})];assert.throws(()=>c.validateAttachments(s,[]));});
test('snapshot preserves deleted evidence; state and attachments roll back atomically',async()=>{const s=fixture();s.transactions=[tx('d','debt',1,{attachmentIds:['a']})];await store.saveStateRecord({revision:1,payload:s},{attachments:[{id:'a',transactionId:'d',creditorId:'c',data:'QQ=='}]});const noFile=c.deepClone(s);noFile.transactions[0].attachmentIds=[];await store.saveStateRecord({revision:2,payload:noFile},{expectedRevision:1,snapshotReason:'Before removal',deleteAttachmentIds:['a']});const snap=(await store.listSnapshots())[0];assert.equal(snap.attachments[0].data,'QQ==');assert.equal(await store.getAttachment('a'),null);await store.saveStateRecord({...snap.record,revision:3},{expectedRevision:2,attachments:snap.attachments});assert.equal((await store.getAttachment('a')).data,'QQ==');assert.equal((await store.getStateRecord()).payload.transactions[0].attachmentIds[0],'a');});
test('failure in attachment mutation aborts the state write too',async()=>{const before=await store.getStateRecord();await assert.rejects(store.saveStateRecord({revision:before.revision+1,payload:{changed:true}},{expectedRevision:before.revision,attachments:[{id:'valid'},{}]}));assert.equal((await store.getStateRecord()).revision,before.revision);assert.equal((await store.getAttachment('a')).data,'QQ==');});
test('concurrent reference writes have unique revision lease',async()=>{const fn=reportSource.slice(reportSource.indexOf('async function persistReportRef('),reportSource.indexOf('function typeLabel('));const rec=await store.getStateRecord();const ctx={...store,...k,localStorage:{setItem(){}},window:{dispatchEvent(){}},Event:globalThis.Event,r:rec,s:rec.payload};vm.createContext(ctx);vm.runInContext(fn,ctx);await vm.runInContext("persistReportRef(r,s,null,{seq:{infographic:1}})",ctx);assert.equal((await store.getStateRecord()).revision,rec.revision+1);await assert.rejects(vm.runInContext("persistReportRef(r,s,null,{seq:{infographic:1}})",ctx),{name:'RevisionConflictError'});});
test('safe-mode restore reencrypts evidence and preserves the current security keys',async()=>{
 const old=await store.getStateRecord(),currentKey=await k.importDek(new Uint8Array(32).fill(1)),backupKey=await k.importDek(new Uint8Array(32).fill(2));const current=fixture();current.meta.revision=old.revision+1;
 const security={sentinel:'current security'};const encryptedRecord=await store.saveStateRecord({id:'current',revision:current.meta.revision,encrypted:true,envelope:await k.encryptJson(current,currentKey),security},{expectedRevision:old.revision});
 const imported=fixture();imported.transactions=[tx('new','debt',700,{attachmentIds:['evidence']})];const file=await k.encryptAttachmentRecord({id:'evidence',transactionId:'new',creditorId:'c',size:1},new Uint8Array([65]),backupKey);
 const {ctx,run}=appContext();Object.assign(ctx,{fixtureRecord:encryptedRecord,currentKey,securityFixture:security,backupKey,importedFixture:imported,fileFixture:file});
 run("record=fixtureRecord;state=null;safeMode=true;dek=currentKey;security=securityFixture;ui.modal={ctx:{state:importedFixture,dek:backupKey,obj:{createdAt:'2026-10-09',attachments:[fileFixture]}}};authorizeProtected=(label,cb)=>{globalThis.restoreCallback=cb};");run('applyRestore()');await ctx.restoreCallback();
 const saved=await store.getStateRecord();assert.deepEqual(saved.security,security);assert.equal((await k.decryptJson(saved.envelope,currentKey)).transactions[0].amountHalalas,700);assert.deepEqual(new Uint8Array(await k.decryptAttachmentBytes(await store.getAttachment('evidence'),currentKey)),new Uint8Array([65]));
});
test('release manifest hashes and relative module imports are complete',()=>{
 const release=JSON.parse(fs.readFileSync(new URL('../LEDGERLY_RELEASE.json',import.meta.url),'utf8'));for(const entry of release.files){const bytes=fs.readFileSync(new URL('../'+entry.name,import.meta.url));assert.equal(bytes.length,entry.bytes);assert.equal(createHash("sha256").update(bytes).digest("hex"),entry.sha256);}
 const dir=new URL('../releases/20261009-integrity-r4/',import.meta.url);for(const name of fs.readdirSync(dir).filter(n=>n.endsWith('.js'))){const src=fs.readFileSync(new URL(name,dir),'utf8');for(const match of src.matchAll(/(?:from\s*|import\s*)['"](\.\/[^'"]+)['"]/g))assert.ok(fs.existsSync(new URL(match[1],dir)),`${name}: ${match[1]}`);}
});
test('install waits for an explicit update and offline navigation uses one cached shell',async()=>{
 const handlers={},shell={cached:true};let skips=0,added=[];const ctx={self:{location:{origin:'https://example.invalid'},clients:{claim:async()=>{}},skipWaiting(){skips++},addEventListener:(name,cb)=>handlers[name]=cb},URL,caches:{open:async()=>({addAll:async list=>{added=list},match:async()=>shell}),keys:async()=>[],delete:async()=>true},fetch:async()=>{throw new Error('offline')}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(new URL('../service-worker.js',import.meta.url),'utf8'),ctx);let done;handlers.install({waitUntil:p=>done=p});await done;assert.equal(skips,0);assert.ok(added.includes('./releases/20261009-integrity-r4/app.3.1.0.js'));let response;handlers.fetch({request:{method:'GET',url:'https://example.invalid/ledgerly-app/',mode:'navigate'},respondWith:p=>response=p});assert.equal(await response,shell);handlers.message({data:{type:'SKIP_WAITING'}});assert.equal(skips,1);
});
function entryContext(id){const t=appContext();t.ctx.fixture=fixture();t.run("state=fixture;record={encrypted:true};security={};");const form=t.dom.window.document.createElement('form');form.id=id;form.innerHTML='<input name="amount" value="100"><input type="file" name="evidence">';t.dom.window.document.getElementById('modal').append(form);t.ctx.form=form;return {...t,form};}
test('core save paths cannot add debt or payment without password even without guard listeners',async()=>{for(const id of ['debtForm','paymentForm']){const t=entryContext(id);t.run('unlockSecurity=async()=>{throw new Error("not authorized")};');await t.run(id==='debtForm'?'saveDebt(form)':'savePayment(form)');assert.ok(t.form.querySelector('[data-entry-authorization]'));assert.equal(t.run('state.transactions.length'),0);assert.equal(t.form.elements.amount.value,'100');}});
test('core authorization rejects wrong password and cancel preserves input and evidence nodes',async()=>{const t=entryContext('debtForm');const file=t.form.querySelector('[type=file]');t.run('unlockSecurity=async()=>{throw new Error("wrong")};');await t.run('verifyNewEntryPassword(form)');t.form.querySelector('[type=password]').value='incorrect';assert.equal(await t.run('verifyNewEntryPassword(form)'),false);assert.match(t.form.querySelector('.form-error').textContent,/Incorrect/);t.form.querySelector('[data-cancel-entry-authorization]').click();assert.equal(t.form.elements.amount.value,'100');assert.equal(t.form.querySelector('[type=file]'),file);assert.equal(await t.run('verifyNewEntryPassword(form)'),false);});
test('core authorization checks every attempt and fails if locked during verification',async()=>{const t=entryContext('paymentForm');t.run('unlockSecurity=async()=>{};');await t.run('verifyNewEntryPassword(form)');t.form.querySelector('[type=password]').value='correct-test';assert.equal(await t.run('verifyNewEntryPassword(form)'),true);assert.equal(t.form.querySelector('[type=password]').value,'');t.run('unlockSecurity=async()=>{sessionEpoch++;state=null};');t.form.querySelector('[type=password]').value='correct-test';assert.equal(await t.run('verifyNewEntryPassword(form)'),false);});
test('image Preview displays inline without downloading and releases plaintext on close',async()=>{
 const t=appContext();t.ctx.fixture=fixture();let downloads=0,revoked=[];t.ctx.URL={createObjectURL:()=> 'blob:test-preview',revokeObjectURL:v=>revoked.push(v)};t.ctx.atob=atob;t.run("state=fixture;getAttachment=async()=>({id:'image',transactionId:'d',name:'Evidence.jpg',type:'image/jpeg',data:'QQ=='});");t.ctx.downloads=0;t.dom.window.HTMLAnchorElement.prototype.click=()=>{t.ctx.downloads++;};await t.run("previewAttachment('image')");assert.equal(t.dom.window.document.querySelector('#attachmentImage').src,'blob:test-preview');assert.equal(t.ctx.downloads,0);assert.equal(t.dom.window.document.querySelector('[data-action="download-attachment"]').textContent,'Download');const bytes=t.run('attachmentPreview.bytes');t.run('closeModal()');assert.deepEqual(revoked,['blob:test-preview']);assert.equal(bytes[0],0);assert.equal(t.dom.window.document.querySelector('#attachmentImage'),null);
});
test('locking while attachment decrypts prevents preview and download',async()=>{
 for(const action of ['previewAttachment','downloadAttachment']){const t=appContext();t.ctx.fixture=fixture();t.ctx.atob=atob;let resolve;t.ctx.pending=new Promise(r=>resolve=r);t.run("state=fixture;getAttachment=()=>pending;");const attempt=t.run(action+"('a')");t.run('sessionEpoch++;state=null;closeModal();');resolve({id:'a',type:'image/jpeg',data:'QQ=='});await attempt;assert.equal(t.dom.window.document.querySelector('#attachmentImage'),null);}
});
test('PDF preview pages clamp at boundaries and render one bounded canvas',async()=>{
 const t=appContext();let renders=0;const canvas=t.dom.window.document.createElement('canvas');canvas.id='attachmentCanvas';canvas.getContext=()=>({});t.dom.window.document.getElementById('modal').append(canvas);for(const id of ['previewPage','previewPrevious','previewNext','previewError']){const el=t.dom.window.document.createElement('button');el.id=id;t.dom.window.document.getElementById('modal').append(el);}t.ctx.pdfFixture={numPages:2,getPage:async()=>({getViewport:({scale})=>({width:1000*scale,height:2000*scale}),render:()=>{renders++;return {promise:Promise.resolve()};},cleanup(){}})};t.run('attachmentPreview={pdf:pdfFixture,page:1};');await t.run('renderAttachmentPage(-1)');assert.equal(t.dom.window.document.getElementById('previewPage').textContent,'Page 1 of 2');assert.equal(canvas.height,1600);await t.run('renderAttachmentPage(1)');assert.equal(t.dom.window.document.getElementById('previewNext').disabled,true);assert.equal(renders,2);
});

test('autonomous acceptance: real form saves 100 debt, 30 payment, 10 decrease, 20 waiver, reversal and atomic creditor merge',async()=>{
 const t=appContext(),s=fixture();s.transactions=[tx('d','debt',10000),tx('p','payment',3000,{allocations:[{debtId:'d',amountHalalas:3000}]})];
 const prior=await store.getStateRecord();const saved=await store.saveStateRecord({id:'current',encrypted:false,revision:prior.revision+1,payload:s},{expectedRevision:prior.revision});Object.assign(t.ctx,{acceptanceState:s,acceptanceRecord:saved});t.run('state=acceptanceState;record=acceptanceRecord;');
 function form(fields){const f=t.dom.window.document.createElement('form');for(const [name,value] of Object.entries(fields)){const i=t.dom.window.document.createElement('input');i.name=name;i.value=value;f.append(i);}t.ctx.acceptanceForm=f;return f;}
 assert.equal(t.run("creditorSummary(state,'c').remaining"),7000);
 form({amount:'10',direction:'decrease',effectiveDate:'2026-10-09'});t.run("ui.modal={creditorId:'c'};");await t.run('saveAdjustment(acceptanceForm)');assert.equal(t.run("creditorSummary(state,'c').remaining"),6000);
 form({amount:'20',effectiveDate:'2026-10-09'});t.run("ui.modal={creditorId:'c'};");await t.run('saveWaiver(acceptanceForm)');assert.equal(t.run("creditorSummary(state,'c').remaining"),4000);assert.equal(t.run("creditorSummary(state,'c').paid"),3000);assert.equal(t.run("creditorSummary(state,'c').waivers"),2000);
 const waiver=t.run("state.transactions.find(x=>x.type==='waiver').id");t.ctx.waiverId=waiver;await t.run("applyReverse(waiverId,{reason:'Automated acceptance',effectiveDate:'2026-10-09'})");assert.equal(t.run("creditorSummary(state,'c').remaining"),6000);assert.equal(t.run("creditorSummary(state,'c').waivers"),0);
 await t.run("applyReverse('p',{reason:'Automated acceptance',effectiveDate:'2026-10-09'})");assert.equal(t.run("creditorSummary(state,'c').remaining"),9000);assert.equal(t.run("creditorSummary(state,'c').paid"),0);await assert.rejects(t.run("applyReverse('p',{reason:'Duplicate',effectiveDate:'2026-10-09'})"));
 await t.run("commit({event:'Synthetic merge target',mutate:async next=>{next.creditors.push({id:'target',name:'Target'});next.templates.push({id:'tp',creditorId:'c'});}})");const before=t.run('overallSummary(state).remaining');await t.run("applyMerge('c','target','Automated acceptance')");assert.equal(t.run('overallSummary(state).remaining'),before);assert.equal(t.run("state.transactions.every(x=>x.creditorId==='target')"),true);assert.equal(t.run("state.templates[0].creditorId"),'target');assert.equal(t.run('validateState(state)'),true);assert.equal((await store.getStateRecord()).payload.creditors.length,1);
 console.log('ACCEPTANCE: 70 → 60 → 40; paid 30; waiver reversal → 60; payment reversal → 90; duplicate reversal rejected; merge preserves total and references.');
});
